BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `reference` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`c_id`	INTEGER,
	`reference`	TEXT
);
INSERT INTO `reference` (id,c_id,reference) VALUES (1,1,'doi:10.1007/s00010-006-2843-9'),
 (2,2,'doi:10.1007/s10998-006-0028-x'),
 (3,3,'https://amc-journal.eu/index.php/amc/article/view/204/192'),
 (4,4,'https://amc-journal.eu/index.php/amc/article/view/204/192'),
 (5,5,'rg:260908716_Polytopes_Derived_from_Sporadic_Simple_Groups'),
 (6,6,'doi:10.26493/1855-3974.455.422'),
 (7,9,'arxiv:1608.04158'),
 (8,10,'ISBN:0198526504'),
 (9,35,'doi:10.1112/S1461157014000424'),
 (10,36,'doi:10.1090/S0025-5718-04-01626-6'),
 (11,18,'ISBN:9789082750010'),
 (12,44,'ISBN:9789082750027'),
 (13,51,'doi:10.1007/s00180-015-0594-6');
CREATE TABLE IF NOT EXISTS `database` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`c_id`	INTEGER
);
INSERT INTO `database` (id,c_id) VALUES (1,21),
 (2,22),
 (3,23),
 (4,24),
 (5,25),
 (6,26),
 (7,27),
 (8,28),
 (9,29),
 (10,30);
CREATE TABLE IF NOT EXISTS `collection_author` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`c_id`	INTEGER NOT NULL,
	`a_id`	INTEGER NOT NULL
);
INSERT INTO `collection_author` (id,c_id,a_id) VALUES (1,1,1),
 (2,1,2),
 (3,2,3),
 (4,3,2),
 (5,3,3),
 (6,3,4),
 (7,4,2),
 (8,4,3),
 (9,4,4),
 (10,5,3),
 (11,5,5),
 (12,6,2),
 (13,6,6),
 (14,7,7),
 (15,9,10),
 (16,9,11),
 (17,8,9),
 (18,10,12),
 (19,10,13),
 (20,11,14),
 (21,12,14),
 (22,13,15),
 (23,13,16),
 (24,14,17),
 (25,16,19),
 (26,17,20),
 (27,17,21),
 (28,18,22),
 (29,19,23),
 (30,19,24),
 (31,21,25),
 (32,21,26),
 (33,21,27),
 (34,21,28),
 (35,21,29),
 (36,21,30),
 (37,21,31),
 (38,21,32),
 (39,21,33),
 (40,21,34),
 (41,22,35),
 (42,28,36),
 (43,28,37),
 (44,28,38),
 (45,29,39),
 (46,31,40),
 (47,31,41),
 (48,32,42),
 (49,32,43),
 (50,32,44),
 (51,16,2),
 (52,33,45),
 (53,34,46),
 (54,34,47),
 (55,36,48),
 (56,36,49),
 (57,37,50),
 (58,38,51),
 (59,39,10),
 (60,40,52),
 (61,41,53),
 (62,42,54),
 (63,43,55),
 (64,43,56),
 (65,45,57),
 (66,44,22),
 (67,46,58),
 (68,47,59),
 (69,48,60),
 (70,49,61),
 (71,50,62),
 (72,50,63),
 (73,50,64),
 (74,51,65),
 (75,51,66),
 (76,51,67),
 (77,52,68),
 (78,52,69),
 (79,52,70);
CREATE TABLE IF NOT EXISTS `collection` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`url`	INTEGER,
	`object_type`	TEXT NOT NULL,
	`number_of_objects`	INTEGER,
	`number_of_datasets`	INTEGER,
	`number_of_contributors`	TEXT,
	`size_compressed`	TEXT,
	`size_uncompressed`	INTEGER,
	`time_to_generate`	INTEGER,
	`provenance`	TEXT,
	`comment`	TEXT,
	`complete`	TEXT,
	`irredundant`	INTEGER,
	`collaborative`	TEXT,
	`decentralised`	TEXT,
	`searchable`	TEXT,
	`selfexplaining`	TEXT,
	`FAIR_summary`	TEXT,
	`findable`	TEXT,
	`accessible`	TEXT,
	`interoperable`	TEXT,
	`reusable`	TEXT
);
INSERT INTO `collection` (id,name,url,object_type,number_of_objects,number_of_datasets,number_of_contributors,size_compressed,size_uncompressed,time_to_generate,provenance,comment,complete,irredundant,collaborative,decentralised,searchable,selfexplaining,FAIR_summary,findable,accessible,interoperable,reusable) VALUES (1,'An Atlas of Abstract Regular Polytopes for Small Almost Simple Groups','https://www.math.auckland.ac.nz/~dleemans/polytopes/','abstract polytope',5354,1,'authors',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'The paper describing the collection (metadata) has a DOI, which links to the website where the dataset is published.  Only certain parts of the dataset are available in a machine readable format','MFTXXMXXTFFT','TTTTTTTTTXXT','FMFFMFFMF','MFTFXTMMMMMM'),
 (2,'An Atlas of Small Regular Polytopes','http://www.abstract-polytopes.com/atlas/index.html','abstract polytope',35974,1,'authors',NULL,NULL,NULL,'Yes','Regular polytopes whose automorphism groups have order less than 2001, excluding 1024 and 1536','Yes, except for the stated exclusions','Yes','No','zipped version of the atlas is made available for download','No, but well indexed','No','Web interface only, but with cut-and-pasteable code for Magma and GAP',NULL,NULL,NULL,NULL),
 (3,'An Atlas of Chiral Polytopes for Small Almost Simple Groups','http://homepages.ulb.ac.be/~dleemans/CHIRAL/index.html','abstract polytope',19212,1,'authors',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (4,'The Atlas of Small Chiral Polytopes','http://www.abstract-polytopes.com/chiral/','abstract polytope',56,1,'authors',NULL,NULL,NULL,'Yes','Chiral polytopes whose regular covers have automorphism groups of order less than 2001, excluding 1024 and 1536','Yes, except for the stated exclusions','Yes','No','No','No, but well indexed','No','Web interface only, but with cut-and-pasteable code for Magma and GAP',NULL,NULL,NULL,NULL),
 (5,'Polytopes Derived from Sporadic Simple Groups','http://www.abstract-polytopes.com/sporpolys/','abstract polytope',6047,1,'authors',NULL,NULL,NULL,'Yes','Regular polytopes whose automorphism groups are sporadic simple groups, with order up to and including that of the Held group','Yes, except for the stated exclusions','Yes','No','A zipped version of the atlas is made available for download','No','No','Web interface only',NULL,NULL,NULL,NULL),
 (6,'An Atlas of Subgroup Lattices of Finite Almost Simple Groups','http://homepages.ulb.ac.be/~dleemans/atlaslat/','lattice','',1,'authors',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (7,'Unlabeled lattices on <=15 nodes','https://www.shsu.edu/mem037/Lattices.html','lattice',171432956,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (8,'Lists of finite lattices (modular, semimodular, graded and geometric)','https://b2share.eudat.eu/records/dbb096da4e364b5e9e37b982431f41de','lattice',17194000000,6,NULL,NULL,NULL,NULL,'https://b2share.eudat.eu/api/files/7794ba17-08ef-4d9a-b35f-4ef6e524b982/00README.txt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (9,'A Census of Edge-Transitive Tetravalent Graphs','http://jan.ucc.nau.edu/~swilson/C4FullSite/index.html','graph',7364,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'There are three kinds of edge-transitive tetravalent graphs, namely: dart-transitive, half-arc-transitive and semisymmetric. This Census inherits completeness in the first two categories from studies by Potočnik, Spiga and Verret. The third category is not known to be complete and we strongly suspect that it is not.','Yes','No',NULL,NULL,NULL,'The paper (part of the metadata) is not yet published (January 2019).  Every graph has a unique identifier (C4[n, i]), an encyclopedic page (the URL is deducible from its identifier).  The dataset is available as a Magma file and the properties as an Excel file.',NULL,NULL,NULL,NULL),
 (10,'An Atlas of Graphs','https://zbmath.org/?q=an%3A1080.05001','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Book',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (11,'Simple k-Angulations','http://www.jooyandeh.com/Combinatorics/Data/K-Angulations.aspx','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (12,'Planar Hypohamiltonian Graphs','http://www.jooyandeh.com/Combinatorics/Data/PlanarHypohamiltonian.aspx','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (13,'A Database of Graphs in Combinatorica Format','http://www3.cs.stonybrook.edu/~skiena/combinatorica/graphs/','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (14,'Regular Graphs','http://www.mathe2.uni-bayreuth.de/markus/reggraphs.html','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (15,'Strongly Regular Graphs on at most 64 vertices','http://www.maths.gla.ac.uk/~es/srgraphs.php','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (16,'An Atlas of primitive geometries of rank 2 for sporadic groups','https://data.adam-journal.eu/apg/','geometry',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (17,'Classification of association schemes with small vertices','http://math.shinshu-u.ac.jp/~hanaki/as/','association scheme',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (18,'An Encyclopedia of Quadri-Figures','https://chrisvantienhoven.nl/mathematics/encyclopedia','quadri-figure',300,NULL,NULL,NULL,NULL,NULL,NULL,'Items dependent on 4 mutually independent points/lines in geometry.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (19,'A Database of Galois polynomials','http://pari.math.u-bordeaux.fr/galpol/','Galois polynomial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (20,'The Knot Atlas','http://katlas.org/wiki/Main_Page','knot',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (21,'ATLAS of Finite Group Representations','http://brauer.maths.qmul.ac.uk/Atlas/v3/','group representation',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (22,'Database of Permutation Pattern Avoidance','https://math.depaul.edu/bridget/patterns.html','permutation pattern',54,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (23,'Encyclopedia of Graphs','http://atlas.gregas.eu/','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (24,'FindStat (The Combinatorial Statistic Finder)','http://www.findstat.org/','combinatorial statistic',1345,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (25,'The House of Graphs','https://hog.grinvin.org/','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (26,'LMFDB, the database of L-functions, modular forms, and related objects','http://www.lmfdb.org/
','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (27,'The On-Line Encyclopedia of Integer Sequences','https://oeis.org/','integer sequence',320000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (28,'QaoS - Querying Algebraic Objects System','http://qaos.math.tu-berlin.de/cgi-bin/qaos/query.scm','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (29,'Small Graph Database','https://jasongrout.org/graph_database','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (30,'The SymbolicData Project','https://symbolicdata.github.io/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (31,'DiscreteZOO','https://github.com/discretezoo','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (32,'The Small Groups library','http://www.icm.tu-bs.de/ag_algebra/software/small/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (33,'Echidna Databases','http://iml.univ-mrs.fr/~kohel/dbs/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Databases for Elliptic Curves and Higher Dimensional Analogues',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (34,'Database of Local Fields','https://math.la.asu.edu/~jj/localfields/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (35,'Database of Number Fields','https://hobbes.la.asu.edu/NFDB/','number field',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (36,'Steiner Triple Systems of order 19','http://pottonen.kapsi.fi/sts19/','Steiner triple system',11084874829,NULL,'39 GB',NULL,NULL,NULL,'algorithm described in paper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (37,'Parameters of Strongly Regular Graphs','https://www.win.tue.nl/~aeb/graphs/srg/srgtab.html','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (38,'Lists of regular maps, hypermaps and polytopes, trivalent symmetric graphs, and surface actions','https://www.math.auckland.ac.nz/~conder/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (39,'Lists of graphs of a prescribed symmetry type and valence, and some other combinatorial and algebraic structures','https://www.fmf.uni-lj.si/~potocnik/work.htm','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (40,'Combinatorial Catalogues','http://staffhome.ecm.uwa.edu.au/~00013890/data.html','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (41,'Combinatorial Data','http://users.cecs.anu.edu.au/~bdm/data/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (42,'Combinatorial Data','http://users.monash.edu.au/~iwanless/data/','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (43,'A Database for Number Fields','http://galoisdb.math.upb.de/','number field',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (44,'Encyclopedia of Polygon Geometry','https://chrisvantienhoven.nl/mathematics/encyclopedia-of-poly-geometry','polygon geometry',15,NULL,NULL,NULL,NULL,NULL,NULL,' Items dependent on n (n=integer) mutually independent points/lines in geometry.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (45,'Encyclopedia of Triangle Centers','http://faculty.evansville.edu/ck6/encyclopedia/ETC.html','triangle center',32000,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (46,'Catalogue of Triangle Cubics','http://bernard.gibert.pagesperso-orange.fr/ctc.html','triangle cubic',1090,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (47,'The Encyclopedia of Polyhedra','http://www.georgehart.com/virtual-polyhedra/vp.html','polyhedron',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (48,'Design Database','http://www.maths.qmul.ac.uk/~lsoicher/designtheory.org/database/','block design',2448,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (49,'Table of Knot Invariants','http://www.indiana.edu/~knotinfo/','knot invariant',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (50,'DistanceRegular.org','http://www.distanceregular.org/','graph',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (51,'Distributome','http://www.distributome.org/','probability distribution',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (52,'SuiteSparse Matrix Collection','https://sparse.tamu.edu/','matrix',2833,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE IF NOT EXISTS `author` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`surname`	TEXT NOT NULL,
	`name`	TEXT NOT NULL,
	`url`	TEXT
);
INSERT INTO `author` (id,surname,name,url) VALUES (1,'Vauthier','Laurence',NULL),
 (2,'Leemans','Dimitri','http://homepages.ulb.ac.be/~dleemans/'),
 (3,'Hartley','Michael','http://dr-mikes-maths.com/maths.html'),
 (4,'Hubard','Isabel','https://www.matem.unam.mx/fsd/hubard'),
 (5,'Hulpke','Alexander','http://www.math.colostate.edu/~hulpke/'),
 (6,'Connor','Thomas',NULL),
 (7,'Malandro','Martin','https://www.shsu.edu/mem037/'),
 (8,'Jipsen','Peter','http://www1.chapman.edu/~jipsen/'),
 (9,'Kohonen','Jukka',''),
 (10,'Potočnik','Primož','https://www.fmf.uni-lj.si/~potocnik/work.htm'),
 (11,'Wilson','Steve','http://jan.ucc.nau.edu/~swilson/'),
 (12,'Read','Ronald',NULL),
 (13,'Wilson','Robin',NULL),
 (14,'Jooyandeh','Reza',NULL),
 (15,'Pemmaraju','Sriram',NULL),
 (16,'Skiena','Steven',NULL),
 (17,'Meringer','Markus',NULL),
 (18,'Spence','Ted',NULL),
 (19,'Rodrigues','Bernardo',NULL),
 (20,'Miyamoto','Izumi',NULL),
 (21,'Hanaki','Akihide',NULL),
 (22,'van Tienhoven','Chris',NULL),
 (23,'Allombert','Bill',NULL),
 (24,'Schein','Igor',NULL),
 (25,'Wilson','Robert',NULL),
 (26,'Walsh','Peter',NULL),
 (27,'Tripp','Jonathan',NULL),
 (28,'Suleiman','Ibrahim',NULL),
 (29,'Parker','Richard',NULL),
 (30,'Norton','Simon',NULL),
 (31,'Nickerson','Simon',NULL),
 (32,'Linton','Steve',NULL),
 (33,'Bray','John',NULL),
 (34,'Abbott','Rachel',NULL),
 (35,'Tenner','Bridget','http://math.depaul.edu/bridget/'),
 (36,'Freundt','Sebastian',NULL),
 (37,'Pauli','Sebastian',NULL),
 (38,'Fraatz','Robert',NULL),
 (39,'Grout','Jason',NULL),
 (40,'Berčič','Katja',NULL),
 (41,'Vidali','Janoš',NULL),
 (42,'Besche','Hans Ulrich',NULL),
 (43,'Eick','Bettina',NULL),
 (44,'O''Brien','Eamonn',NULL),
 (45,'Kohel','David','http://iml.univ-mrs.fr/~kohel/'),
 (46,'Jones','John','https://hobbes.la.asu.edu/'),
 (47,'Roberts','David P.',NULL),
 (48,'Kaski','Petteri',NULL),
 (49,'Östergård','Patric','https://users.aalto.fi/~pat/'),
 (50,'Brouwer','Andries','https://www.win.tue.nl/~aeb/'),
 (51,'Conder','Marston','https://www.math.auckland.ac.nz/~conder/'),
 (52,'Royle','Gordon','https://research-repository.uwa.edu.au/en/persons/gordon-royle'),
 (53,'McKay','Brendan','http://users.cecs.anu.edu.au/~bdm/'),
 (54,'Wanless','Ian','http://users.monash.edu.au/~iwanless/'),
 (55,'Klüners','Jürgen','http://www2.math.uni-paderborn.de/people/juergen-klueners.html'),
 (56,'Malle','Gunter','http://www.mathematik.uni-kl.de/~malle/en/index.html'),
 (57,'Kimberling','Clark','http://faculty.evansville.edu/ck6/'),
 (58,'Gibert','Bernard','http://bernard.gibert.pagesperso-orange.fr/index.html'),
 (59,'Hart','George W.','http://www.georgehart.com/index.html'),
 (60,'Dobcsányi','Peter',NULL),
 (61,'Livingston','Chuck','http://php.indiana.edu/~livingst/'),
 (62,'Bailey','Robert','http://www2.grenfell.mun.ca/rbailey'),
 (63,'Jackson','Adam',NULL),
 (64,'Weir','Courtney ',NULL),
 (65,'Dinov','Ivo','http://www.socr.umich.edu/people/dinov/'),
 (66,'Pearl','Dennis','http://www.stat.osu.edu/~dkp/'),
 (67,'Siegrist ','Kyle','http://www.math.uah.edu/~siegrist/'),
 (68,'Davis','Tim','http://faculty.cse.tamu.edu/davis'),
 (69,'Hu','Yifan','http://yifanhu.net/'),
 (70,'Kolodziej','Scott','http://www.scottkolo.com/');
COMMIT;
